# Demo: Drawing samples from a distribution and using other description functions

In [2]:
from scipy import stats
import numpy as np

In [12]:
l = 2.0
a = 5.0
gamma_rv = stats.gamma(a, scale=1/l)

In [17]:
sample1 = gamma_rv.rvs(size=5)
sample2 = gamma_rv.rvs(size=5)

sample1, sample2

(array([ 2.37373375,  4.25824124,  1.00456948,  1.1914439 ,  1.48322083]),
 array([ 1.27166325,  0.65757583,  6.39410137,  2.00784   ,  3.030782  ]))

In [18]:
# set random seed

sample1 = gamma_rv.rvs(size=5)

sample2 = gamma_rv.rvs(size=5)

sample1, sample2

(array([ 1.84251696,  4.77201057,  3.22955927,  0.70860623,  2.77611568]),
 array([ 1.84251696,  4.77201057,  3.22955927,  0.70860623,  2.77611568]))

In [24]:
mean =
median =
std =
var =
moment3 =
skewness, kurt =

print('Mean={}, Median={}, Std={}, Var={}'.format(mean, median,
                                                  std, var))
print('3rd moment={}'.format(moment3))
print('Skewness={}, Kurtosis={}'.format(skewness, kurt))

Mean=2.5, Median=2.3354544414, Std=1.11803398875, Var=1.25
3rd moment=26.25
Skewness=0.894427191, Kurtosis=1.2
